name: merge_stack_trace
description: Merge StackTrace(s)
version: 1.0.0
repository: https://github.com/erlangparasu/merge_stack_trace
homepage: https://github.com/erlangparasu/merge_stack_trace

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
# dependencies:
#   # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
